# publish.yml

name: "Release"

on:
  push:
    tags:
      - "*"
permissions:
  contents: write

jobs:
  run:
    name: "Build and publish release"
    runs-on: ubuntu-latest
    matrix:
      python-version:
        - "3.11"
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: uv.lock

      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install  ${{ matrix.python-version }}

      - name: Build
        run: uv build

      - name: Publish
        run: uv publish -t ${{ secrets.UV_PUBLISH_TOKEN }}
